scan_timeout = 10

[character]
success_symbol = "[âžœ](bold green)"
vicmd_symbol = "[ðŸ œ](blue)"
error_symbol = "[âœ—](bold red)"

[time]
disabled = true

[python]
python_binary = "python3"

[git_status]
disabled = true
